[theme]
base = "dark"
primaryColor = "#2e74fd"
backgroundColor = "#05070e"
secondaryBackgroundColor = "#0a0e1a"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 4096

[browser]
gatherUsageStats = false
